Add header to cuctf_2019.html
CUCyber/cuctf.io pull request #19
Opened 2020-06-03 16:56 UTC by Jacob-Mellichamp

Something was off about this page, and then I realized "ahh yes, it needs a header!" Nothing big here, just a one lined patch

2020-06-03 17:05 UTC, lilyinstarlight commented
Yeah page headings need to actually be consistent as apparently they're different on every single page right now. Register is also missing a heading. We should probably have a discussion of which style we like best and enforce that for all of the headings.

You're adding one that looks the same as the about page and I think I like that one best. Does anyone else have any opinions?

After picking a style, we'll need to update about, sponsors, faqs, cuctf 2019, our team, and register to all have their top heading match that.

2020-06-03 17:17 UTC, Jacob-Mellichamp commented
Yeah, `<h1 class="text-accent-4 center">` should be the style for each. There's not really a noticeable difference between the styles other than size. I do like the Team header being orange though... adds a little uniqueness to the website.

2020-06-04 21:53 UTC, mmaekr approved these changes

2020-06-05 14:15 UTC, lilyinstarlight requested changes
See #20 which includes your commit in this PR

2020-06-05 20:22 UTC, closed without merging