Sponsor Update
CUCyber/cuctf.io pull request #22
Opened 2020-06-15 00:14 UTC by Jacob-Mellichamp

View the page at https://sponsor.dev.cuctf.io

Main take aways:
  - Added a link to the CUCTF Sponsor Packet on sponsors.html
  - Reformatted sponsors.html
  - Added CUCTF 2019 sponsors to the bottom of CUCTF_2019.html
  - Minor changes to the formatting of CUCTF_2019.html
  - Added logos images and packet pdf to the public folder. 

Let me know if this is ready for a merge or if additional work is needed

2020-06-15 10:13 UTC, lilyinstarlight requested changes
I'm putting this here mostly as a few notes for changing and merge notes but I'll provide a more specific review later. The merge notes below are for me or whoever is merging and the more specific review later will be made for the changes below. Adding last year's sponsors and the packet though is a much appreciated change!

### Changes

- I'm pretty sure at least Ally's logo and possibly others need to be against a white background per their brand policy. I can double check this later and provide a list of requirements and suggestions.
- Sponsor images need `alt` attribute filled out
- Move `style` attribute on `p` tag to either id or class style in stylesheet


### Merge notes

- There are a lot of errant spaces (only affects the code readability but not presentation) so I'll probably get rid of those before merge
- Remove .DS_Store files before merge
- Rebase on dev before merge

2020-06-15 10:20 UTC, houstdav000 commented
Just a recommendation, but I'd suggest creating a global .gitignore_global file to prevent adding .DS_Store files like [mine](https://github.com/houstdav000/dotfiles/blob/master/.gitignore_global)

2020-06-16 03:32 UTC, Jacob-Mellichamp commented
Pushed Changes to the branch:
  - Removed all .DS_Store files
  - Made Level 2 sponsors have white background
  - moved `<p style="">` to css class
  - added alt text to sponsor images
  - removed CUCTF Sponsor Benefits image from `/public/2020`

2020-06-16 15:18 UTC, mmaekr approved these changes

2020-06-17 02:27 UTC, closed without merging